export const ActionTypes = {
  GLOBAL_UPDATE: 'GLOBAL_UPDATE',	
  JOURNAL_UPDATE: 'JOURNAL_UPDATE',
  LOAD_JOURNAL_DETAIL: 'LOAD_JOURNAL_DETAIL',
  USER_UPDATE:'USER_UPDATE',
  LOAD_USER_DETAIL:'LOAD_USER_DETAIL',
  LOGIN:'LOGIN',
  LOGOUT:'LOGOUT'
};